services:
  amigo:
    build: .
    container_name: amigo_sim
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=1
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
      - HOST_USER=${HOST_USER:-developer}
    working_dir: /workspace
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./:/workspace:rw
      - catkin_build:/workspace/build
      - catkin_devel:/workspace/devel
volumes:
  catkin_build:
  catkin_devel:
