version: '3.8'

services:
  ros:
    build: .
    image: amigobot:noetic
    # Mount the repo root into the container so your IDE edits are reflected immediately
    volumes:
      - ./:/workspace:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - HOST_UID=${UID}
      - HOST_GID=${GID}
      - DISPLAY=${DISPLAY}
    network_mode: "host"
    tty: true
    stdin_open: true
    working_dir: /workspace
    # If you need access to hardware (GPU, serial devices) add devices or privileged: true
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    # privileged: true

